// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7meOusz8ykfX9-uGGK50bkKZcrE2f0xc',
    appId: '1:686130837530:web:235be55e9b46a0685eb9a3',
    messagingSenderId: '686130837530',
    projectId: 'chat-app-35b56',
    authDomain: 'chat-app-35b56.firebaseapp.com',
    storageBucket: 'chat-app-35b56.appspot.com',
    measurementId: 'G-CF4JVTT29M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-6KR2EPHrsSkr_g6fWEkfsngfOZtGiaQ',
    appId: '1:686130837530:android:9ec0b6b8a79487955eb9a3',
    messagingSenderId: '686130837530',
    projectId: 'chat-app-35b56',
    storageBucket: 'chat-app-35b56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNuMVwQ5Q4M6gtJEgSUDx5gPGiVb-a7tw',
    appId: '1:686130837530:ios:1e90fa944268a3dd5eb9a3',
    messagingSenderId: '686130837530',
    projectId: 'chat-app-35b56',
    storageBucket: 'chat-app-35b56.appspot.com',
    iosClientId: '686130837530-7us4e6cgj3p2n5vos0s341rbqc09n2oe.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNuMVwQ5Q4M6gtJEgSUDx5gPGiVb-a7tw',
    appId: '1:686130837530:ios:1e90fa944268a3dd5eb9a3',
    messagingSenderId: '686130837530',
    projectId: 'chat-app-35b56',
    storageBucket: 'chat-app-35b56.appspot.com',
    iosClientId: '686130837530-7us4e6cgj3p2n5vos0s341rbqc09n2oe.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7meOusz8ykfX9-uGGK50bkKZcrE2f0xc',
    appId: '1:686130837530:web:b072e4495774b27c5eb9a3',
    messagingSenderId: '686130837530',
    projectId: 'chat-app-35b56',
    authDomain: 'chat-app-35b56.firebaseapp.com',
    storageBucket: 'chat-app-35b56.appspot.com',
    measurementId: 'G-S7MJDLVL83',
  );

}